language: csharp
mono: none
dotnet: 2.1.4
dist: trusty
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
os:
  - linux
  - osx
osx_image: xcode8.3
script:
  - ./build.sh
